#!/bin/bash

echo "=== Current Scroll Settings ==="
echo ""
echo "Global scroll direction (0=traditional, 1=natural):"
defaults read NSGlobalDomain com.apple.swipescrolldirection 2>/dev/null || echo "Not set (default: 1/natural)"
echo ""
echo "Magic Mouse vertical scroll:"
defaults read com.apple.AppleMultitouchMouse MouseVerticalScroll 2>/dev/null || echo "Not set"
echo ""
echo "Bluetooth mouse vertical scroll:"
defaults read com.apple.driver.AppleBluetoothMultitouch.mouse MouseVerticalScroll 2>/dev/null || echo "Not set"
echo ""
echo "=== To fix manually ==="
echo "For traditional scrolling (Windows-like), run:"
echo "  defaults write NSGlobalDomain com.apple.swipescrolldirection -int 0"
echo "  killall Finder"
echo ""
echo "For natural scrolling (iOS-like), run:"
echo "  defaults write NSGlobalDomain com.apple.swipescrolldirection -int 1"
echo "  killall Finder"