# Inspired heavily by:
# https://github.com/joshmedeski/dotfiles/blob/main/.config/aerospace/aerospace.toml

# after-login-command = []
# after-startup-command = []
after-startup-command = [
'exec-and-forget /opt/homebrew/bin/borders active_color=0xfff5f543 inactive_color=0xff3b8eea width=8.0'
]
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# TODO: learn what is this?
# non-empty-workspaces-root-containers-layout-on-startup = 'smart'

accordion-padding = 0
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodness#disable-hide-app
automatically-unhide-macos-hidden-apps = true

# Gaps between windows (inner-*) and between monitor edges (outer-*).
[gaps]
inner.horizontal = 8
inner.vertical =   8
outer.left =       5
outer.bottom =     5
outer.top =        5
outer.right =      5

[mode.main.binding]

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# TODO: is this helpful? How does it work?
# alt-shift-n = 'split opposite'
alt-shift-minus = 'resize smart -100'
alt-shift-equal = 'resize smart +100'

# A huge stretch for mnemonics, but works with CapsLock as Hyper, plus right hand Qwerty.
# T = Terminal (currently Kitty), Tmux
# Y = YDE (VSCode, Webstorm)
# U = Utilities (Finder, Preview, Snagit)
# I = Internet (browsers)
# O = Office (Excel, Word)
# P = Productivity (helpers like SnagIt)
# [ = Communication (Teams, Outlook)

# This binds a series of commands - move to workspace U, then change to workspace U
alt-shift-cmd-ctrl-5 = ['move-node-to-workspace T', 'workspace T']
alt-shift-cmd-ctrl-6 = ['move-node-to-workspace Y', 'workspace Y']
alt-shift-cmd-ctrl-7 = ['move-node-to-workspace U', 'workspace U']
alt-shift-cmd-ctrl-8 = ['move-node-to-workspace I', 'workspace I']
alt-shift-cmd-ctrl-9 = ['move-node-to-workspace O', 'workspace O']
alt-shift-cmd-ctrl-0 = ['move-node-to-workspace P', 'workspace P']
alt-shift-cmd-ctrl-minus = ['move-node-to-workspace [', 'workspace [']

alt-shift-cmd-ctrl-t = 'workspace T'
alt-shift-cmd-ctrl-y = 'workspace Y'
alt-shift-cmd-ctrl-u = 'workspace U'
alt-shift-cmd-ctrl-i = 'workspace I'
alt-shift-cmd-ctrl-o = 'workspace O'
alt-shift-cmd-ctrl-p = 'workspace P'
alt-shift-cmd-ctrl-leftSquareBracket = 'workspace ['

alt-shift-cmd-ctrl-h = 'workspace-back-and-forth'
alt-shift-cmd-ctrl-l = 'move-workspace-to-monitor --wrap-around next'

alt-shift-cmd-ctrl-semicolon = 'mode move'
alt-shift-cmd-ctrl-n = 'layout accordion horizontal vertical'
alt-shift-cmd-ctrl-m = 'layout tiles horizontal vertical'

[mode.move.binding]
esc = ['mode main']
enter = ['mode main']
e = 'layout accordion horizontal vertical'
h = 'move left'
j = 'move down'
k = 'move up'
l = 'move right'
f = 'fullscreen'
t = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
b = 'balance-sizes'

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = 'move-node-to-workspace T'

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace Y'

[[on-window-detected]]
if.app-id = 'com.jetbrains.WebStorm'
run = 'move-node-to-workspace Y'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'move-node-to-workspace U'

[[on-window-detected]]
if.app-id = 'com.apple.Preview'
run = 'move-node-to-workspace U'

[[on-window-detected]]
if.app-id = 'com.electron.dockerdesktop'
run = 'move-node-to-workspace U'

[[on-window-detected]]
if.app-id = 'com.jamfsoftware.selfservice.mac'
run = 'move-node-to-workspace U'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = "move-node-to-workspace I"

[[on-window-detected]]
if.app-id = 'com.microsoft.Excel'
run = 'move-node-to-workspace O'

[[on-window-detected]]
if.app-id = 'com.microsoft.Word'
run = 'move-node-to-workspace O'

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = "move-node-to-workspace P"

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = 'move-node-to-workspace ['

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = 'move-node-to-workspace ['