#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/generate-brewfile.sh <output-file> <config> [<config> ...]

Examples:
  scripts/generate-brewfile.sh Brewfile shared/shell host/common host/personal
  scripts/generate-brewfile.sh Brewfile.posix shared/shell shared/git focus/kubernetes
EOF
}

if [[ $# -lt 2 ]]; then
  usage
  exit 1
fi

output_file="$1"
shift

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

resolve_config_file() {
  local config="$1"
  local candidate="$config"

  if [[ "$candidate" != *.yaml ]]; then
    candidate="${candidate}.yaml"
  fi

  if [[ -f "$candidate" ]]; then
    printf '%s\n' "$candidate"
    return 0
  fi

  if [[ -f "$repo_root/_configs/$candidate" ]]; then
    printf '%s\n' "$repo_root/_configs/$candidate"
    return 0
  fi

  printf 'ERROR: Could not find config: %s\n' "$config" >&2
  return 1
}

taps_tmp="$(mktemp)"
brews_tmp="$(mktemp)"
casks_tmp="$(mktemp)"
mas_tmp="$(mktemp)"

cleanup() {
  rm -f "$taps_tmp" "$brews_tmp" "$casks_tmp" "$mas_tmp"
}
trap cleanup EXIT

for config in "$@"; do
  cfg_file="$(resolve_config_file "$config")"

  yq -r '
    .tools // {} | to_entries[]
    | select(.value.manager == "brew")
    | select(.value.type == "tap")
    | .key
  ' "$cfg_file" >>"$taps_tmp"

  yq -r '
    .tools // {} | to_entries[]
    | select(.value.manager == "brew")
    | select(.value.type == "package")
    | .key
  ' "$cfg_file" >>"$brews_tmp"

  yq -r '
    .tools // {} | to_entries[]
    | select(.value.manager == "brew")
    | select(.value.type == "cask")
    | .key
  ' "$cfg_file" >>"$casks_tmp"

  yq -r '
    .tools // {} | to_entries[]
    | select(.value.manager == "mas")
    | select((.value.app_id // "") != "")
    | .key + "\t" + (.value.app_id | tostring)
  ' "$cfg_file" >>"$mas_tmp"
done

{
  echo "# Generated by scripts/generate-brewfile.sh"
  echo "# Source configs: $*"
  echo

  if [[ -s "$taps_tmp" ]]; then
    echo "# Homebrew taps"
    sort -u "$taps_tmp" | sed '/^[[:space:]]*$/d' | while read -r tap; do
      printf 'tap "%s"\n' "$tap"
    done
    echo
  fi

  if [[ -s "$brews_tmp" ]]; then
    echo "# Homebrew formulae"
    sort -u "$brews_tmp" | sed '/^[[:space:]]*$/d' | while read -r formula; do
      printf 'brew "%s"\n' "$formula"
    done
    echo
  fi

  if [[ -s "$casks_tmp" ]]; then
    echo "# Homebrew casks"
    sort -u "$casks_tmp" | sed '/^[[:space:]]*$/d' | while read -r cask; do
      printf 'cask "%s"\n' "$cask"
    done
    echo
  fi

  if [[ -s "$mas_tmp" ]]; then
    echo "# Mac App Store apps"
    sort -u "$mas_tmp" | sed '/^[[:space:]]*$/d' | while IFS=$'\t' read -r app_name app_id; do
      printf 'mas "%s", id: %s\n' "$app_name" "$app_id"
    done
    echo
  fi
} >"$output_file"

printf 'Generated %s\n' "$output_file"
