#!/usr/bin/env bash
set -euo pipefail

DRY_RUN="${DRY_RUN:-false}"
OUTPUT_FILE="${OUTPUT_FILE:-}"
CONFIG_FILES=()

usage() {
  local exit_code=${1:-0}

  cat <<'EOF'
Usage: scripts/generate-brewfile.sh [options]
Usage: scripts/generate-brewfile.sh <output-file> <config> [<config> ...]

Generate a Brewfile from one or more config bundles.

Options:
  -c, --config <name>        Add configuration file to include (repeatable)
  -d, --dry-run              Print the generated Brewfile instead of writing it
  -h, --help                 Show this help message
  -o, --output-file <path>   Output Brewfile path

Examples:
  scripts/generate-brewfile.sh -o Brewfile -c shared/shell -c host/common -c host/personal
  scripts/generate-brewfile.sh --dry-run -o Brewfile.posix -c shared/git -c focus/kubernetes
  scripts/generate-brewfile.sh Brewfile shared/shell host/common host/personal
EOF

  exit "$exit_code"
}

error() {
  echo "Error: $*" >&2
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    error "Required command not found: $1"
    exit 1
  fi
}

resolve_config_file() {
  local config="$1"
  local candidate="$config"

  if [[ "$candidate" != *.yaml ]]; then
    candidate="${candidate}.yaml"
  fi

  if [[ -f "$candidate" ]]; then
    printf '%s\n' "$candidate"
    return 0
  fi

  if [[ -f "$REPO_ROOT/_configs/$candidate" ]]; then
    printf '%s\n' "$REPO_ROOT/_configs/$candidate"
    return 0
  fi

  error "Could not find config: $config"
  return 1
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case $1 in
      -c|--config)
        if [[ -n "${2:-}" && ! "$2" =~ ^- ]]; then
          CONFIG_FILES+=("$2")
          shift 2
        else
          error "--config requires a configuration name"
          usage 1
        fi
        ;;
      -d|--dry-run)
        DRY_RUN=true
        shift
        ;;
      -o|--output-file)
        if [[ -n "${2:-}" && ! "$2" =~ ^- ]]; then
          OUTPUT_FILE="$2"
          shift 2
        else
          error "--output-file requires a path"
          usage 1
        fi
        ;;
      -h|--help)
        usage 0
        ;;
      -*)
        error "Unknown option: $1"
        usage 1
        ;;
      *)
        break
        ;;
    esac
  done

  if [[ $# -gt 0 ]]; then
    if [[ -z "$OUTPUT_FILE" ]]; then
      OUTPUT_FILE="$1"
      shift
    fi
    while [[ $# -gt 0 ]]; do
      CONFIG_FILES+=("$1")
      shift
    done
  fi

  if [[ -z "$OUTPUT_FILE" ]]; then
    error "An output file is required"
    usage 1
  fi

  if [[ ${#CONFIG_FILES[@]} -eq 0 ]]; then
    error "At least one config is required"
    usage 1
  fi
}

generate_brewfile() {
  local output_file="$1"
  local taps_tmp
  local brews_tmp
  local casks_tmp
  local mas_tmp
  local config
  local cfg_file

  taps_tmp="$(mktemp)"
  brews_tmp="$(mktemp)"
  casks_tmp="$(mktemp)"
  mas_tmp="$(mktemp)"

  cleanup_files+=("$taps_tmp" "$brews_tmp" "$casks_tmp" "$mas_tmp")

  for config in "${CONFIG_FILES[@]}"; do
    cfg_file="$(resolve_config_file "$config")"

    yq -r '
      .tools // {} | to_entries[]
      | select(.value.manager == "brew")
      | select(.value.type == "tap")
      | .key
    ' "$cfg_file" >>"$taps_tmp"

    yq -r '
      .tools // {} | to_entries[]
      | select(.value.manager == "brew")
      | select(.value.type == "package")
      | .key
    ' "$cfg_file" >>"$brews_tmp"

    yq -r '
      .tools // {} | to_entries[]
      | select(.value.manager == "brew")
      | select(.value.type == "cask")
      | .key
    ' "$cfg_file" >>"$casks_tmp"

    yq -r '
      .tools // {} | to_entries[]
      | select(.value.manager == "mas")
      | select((.value.app_id // "") != "")
      | .key + "\t" + (.value.app_id | tostring)
    ' "$cfg_file" >>"$mas_tmp"
  done

  {
    echo "# Generated by scripts/generate-brewfile.sh"
    echo "# Source configs: ${CONFIG_FILES[*]}"
    echo

    if [[ -s "$taps_tmp" ]]; then
      echo "# Homebrew taps"
      sort -u "$taps_tmp" | sed '/^[[:space:]]*$/d' | while read -r tap; do
        printf 'tap "%s"\n' "$tap"
      done
      echo
    fi

    if [[ -s "$brews_tmp" ]]; then
      echo "# Homebrew formulae"
      sort -u "$brews_tmp" | sed '/^[[:space:]]*$/d' | while read -r formula; do
        printf 'brew "%s"\n' "$formula"
      done
      echo
    fi

    if [[ -s "$casks_tmp" ]]; then
      echo "# Homebrew casks"
      sort -u "$casks_tmp" | sed '/^[[:space:]]*$/d' | while read -r cask; do
        printf 'cask "%s"\n' "$cask"
      done
      echo
    fi

    if [[ -s "$mas_tmp" ]]; then
      echo "# Mac App Store apps"
      sort -u "$mas_tmp" | sed '/^[[:space:]]*$/d' | while IFS=$'\t' read -r app_name app_id; do
        printf 'mas "%s", id: %s\n' "$app_name" "$app_id"
      done
      echo
    fi
  } >"$output_file"
}

cleanup() {
  local path
  for path in "${cleanup_files[@]:-}"; do
    rm -f "$path"
  done
}

main() {
  local generated_file

  parse_args "$@"
  require_command yq

  generated_file="$(mktemp)"
  cleanup_files=("$generated_file")
  trap cleanup EXIT

  generate_brewfile "$generated_file"

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "[dry-run] Would write $OUTPUT_FILE"
    echo
    cat "$generated_file"
    return 0
  fi

  mkdir -p "$(dirname "$OUTPUT_FILE")"
  cp "$generated_file" "$OUTPUT_FILE"
  printf 'Generated %s\n' "$OUTPUT_FILE"
}

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cleanup_files=()

main "$@"
