name: Test Install Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install BATS (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y bats
    
    - name: Install BATS (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install bats-core
    
    - name: Run tests
      run: |
        ./test/run_tests.sh
    
    - name: Test dry run
      run: |
        ./install.sh -d -v
    
  shellcheck:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install ShellCheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
    
    - name: Run ShellCheck
      run: |
        shellcheck install.sh || true
        find test -name "*.bash" -o -name "*.bats" | xargs shellcheck || true